// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("MyCsNuget")]
[assembly: AssemblyProduct("MyNuget")]
[assembly: AssemblyDescription("Silly NuGet package")]
[assembly: AssemblyVersion("1.2.3")]
[assembly: AssemblyFileVersion("1.2.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "MyCsNuget";
        internal const System.String AssemblyProduct = "MyNuget";
        internal const System.String AssemblyDescription = "Silly NuGet package";
        internal const System.String AssemblyVersion = "1.2.3";
        internal const System.String AssemblyFileVersion = "1.2.3";
    }
}
