// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MyFsNuget")>]
[<assembly: AssemblyProductAttribute("MyNuget")>]
[<assembly: AssemblyDescriptionAttribute("Silly NuGet package")>]
[<assembly: AssemblyVersionAttribute("1.2.3")>]
[<assembly: AssemblyFileVersionAttribute("1.2.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MyFsNuget"
    let [<Literal>] AssemblyProduct = "MyNuget"
    let [<Literal>] AssemblyDescription = "Silly NuGet package"
    let [<Literal>] AssemblyVersion = "1.2.3"
    let [<Literal>] AssemblyFileVersion = "1.2.3"
